AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the database layer, DynamoDB tables 

Resources:

  Reservations:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Reservations"
      AttributeDefinitions: 
        - AttributeName: "resaid"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "resaid"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Holidays:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Holidays"
      AttributeDefinitions: 
        - AttributeName: "hid"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "hid"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
